# Generated by Django 4.1.1 on 2023-02-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('descripton', models.TextField(blank=True)),
                ('price', models.FloatField(default=0)),
                ('category', models.CharField(max_length=250)),
                ('stock', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name',),
            },
        ),
    ]
