# Generated by Django 4.1.1 on 2023-03-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_product_user'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sproduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.seller_product'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='sproduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.seller_product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='sproduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.seller_product'),
        ),
    ]
