# Generated by Django 4.1.7 on 2023-05-09 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0022_alter_account_approved_staff_alter_account_is_staff_and_more'),
        ('cart', '0003_remove_cart_sproduct_remove_orderplaced_sproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antiqueapp.address'),
        ),
    ]
