# Generated by Django 4.1.7 on 2023-05-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0022_alter_account_approved_staff_alter_account_is_staff_and_more'),
        ('cart', '0004_orderplaced_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='antiqueapp.address'),
        ),
    ]
