# Generated by Django 4.1.1 on 2023-03-07 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0003_remove_account_is_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250, unique=True)),
                ('lname', models.CharField(max_length=250, unique=True)),
                ('street', models.TextField(blank=True)),
                ('city', models.TextField(default=0)),
                ('state', models.CharField(max_length=250)),
                ('zip', models.IntegerField(default=1)),
                ('phone', models.BigIntegerField(default=0)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
