# Generated by Django 4.1.1 on 2023-03-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0005_remove_address_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='fname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='address',
            name='lname',
            field=models.CharField(max_length=250),
        ),
    ]
