# Generated by Django 4.1.1 on 2023-03-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0007_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
