# Generated by Django 4.1.7 on 2023-04-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0013_remove_product_descripton_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descripton',
        ),
    ]
