# Generated by Django 4.1.7 on 2023-04-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0014_rename_description_product_descripton'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
