# Generated by Django 4.1.7 on 2023-04-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0019_alter_account_is_active_alter_account_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deal_of_day',
            field=models.BooleanField(default=False),
        ),
    ]
